# Generated by Django 3.1.4 on 2022-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Conversation', max_length=120, verbose_name='subject'),
        ),
    ]
